apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: easgwnzk2-go-gitops
  description: This is GitOps manifest for easgwnzk2-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=easgwnzk2-go
    backstage.io/kubernetes-id: easgwnzk2-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: easgwnzk2-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:easgwnzk2-go
