apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: easgwnzk2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-go:38ea0985ad631f1eb619e994e924f4b172d1d8c0@sha256:a14dcd0f2280d65ff9da2aa57950029ac461f702a16aa3ddd3abf669153d5793
          name: container-image
